// This file is auto-generated by TanStack Router
// DO NOT EDIT THIS FILE MANUALLY

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRoute } from './routes/dashboard'
import { Route as AboutRoute } from './routes/about'
import { Route as IndexRoute } from './routes/index'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutRoute
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardRoute
      parentRoute: typeof rootRoute
    }
  }
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren([])
const AboutRouteWithChildren = AboutRoute._addFileChildren([])
const IndexRouteWithChildren = IndexRoute._addFileChildren([])

export const routeTree = rootRoute._addFileChildren([
  IndexRouteWithChildren,
  AboutRouteWithChildren,
  DashboardRouteWithChildren,
])
